version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - bookslot_data:/app/sql_app.db # For SQLite database persistence
      - ./locales:/app/locales # Mount locales for easier translation updates
    command: gunicorn src.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000

volumes:
  bookslot_data: {}
