version: '3.8'

services:
  bookslot_app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "src.main:app"]